### ISSUE TITLE
"The apphook is not registered any more..."

### ISSUE THREAD

**Issue by stuaxo** [beniwohli/django-cms-search#17]
I'm new to haystack + django cms; so not sure what an AppHook is.

What does this mean; do I need to do something to make the search work ?

**Comment by Lacrymology** [comment]
The apphook will provide haystack's urls into a django-cms page. If you want to have a "search page" and hook the urls like that (which would be the "standard" way of doing it with django-cms), you'll need to register the apphook, and then hook it into a CMS page.

Otherwise you can hook the haystack views directly onto your urls.py file and use it in some other way
